services:
  react-vite-app:
    build: .  # Build the app from the Dockerfile in the current directory
    ports:
      - "3000:3000"  # Maps port 3000 from the container to localhost
    volumes:
      - .:/react-vite-app  # Mount the current directory into the container for live code updates
      - node_modules:/react-vite-app/node_modules  # Use a named volume for node_modules to avoid conflicts
    environment:
      - NODE_ENV=development  # Set environment variables if needed
    command: npm run dev  # Override the default command to start the app in development mode
    networks:
      - app-network

volumes:
  node_modules:  # Defines a named volume for node_modules

networks:
  app-network:
    driver: bridge