services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es01
      - discovery.type=single-node
      - xpack.security.enabled=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=http://18.142.183.202:3000
      - http.cors.allow-credentials=true
      - http.cors.allow-headers=Authorization,X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Accept,x-elastic-client-meta
      - http.cors.allow-methods=OPTIONS,HEAD,GET,POST,PUT,DELETE
      - "processors=1"
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always

volumes:
  esdata01:
    driver: local